name: CI Dependency Caching

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-06fa6be

      - name: Install dependencies on cache miss
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: |
          echo "Cache not found. Simulating dependency installation."
          npm install -g lodash

      - name: prime-cache-06fa6be
        run: echo "Cache hit status was: ${{ steps.cache-npm.outputs.cache-hit }}"
