name: Cache Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual run from the Actions tab

jobs:
  cache-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: prime-cache-06fa6be
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-06fa6be
          restore-keys: |
            cache-

      - name: Display cache hit/miss
        run: echo "Cache hit = ${{ steps.cache-step.outputs.cache-hit }}"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements.txt found"
          echo "Dependencies installed."

      - name: Verify setup
        run: |
          python --version
          pip list
